name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
      run: |
        echo ${{secrets.ARXIV_QUERY}} | sed 's/./& /g'
